export const INPAGE_PROVIDER_SETTINGS_EVENT = 'INPAGE_PROVIDER_SETTINGS_EVENT';
export const INPAGE_PROVIDER_RESPONSE_EVENT = 'INPAGE_PROVIDER_RESPONSE_EVENT';
export const INPAGE_PROVIDER_ERROR_EVENT = 'INPAGE_PROVIDER_ERROR_EVENT';
export const INPAGE_PROVIDER_REQUEST_EVENT = 'INPAGE_PROVIDER_REQUEST_EVENT';
