export const CHANGE_INIT_STATUS = 'CHANGE_INIT_STATUS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';

export default {
  CHANGE_INIT_STATUS,
  ADD_TRANSACTION,
  REMOVE_TRANSACTION,
};
