export const CHANGE_INJECT_STATUS = 'CHANGE_INJECT_STATUS';
export const ADD_REQUEST = 'ADD_REQUEST';
export const REMOVE_REQUEST = 'REMOVE_REQUEST';

export default {
  CHANGE_INJECT_STATUS,
  ADD_REQUEST,
  REMOVE_REQUEST,
};
