export const CHANGE_INJECT_STATUS = 'CHANGE_INJECT_STATUS';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

export default {
  CHANGE_INJECT_STATUS,
  ADD_MESSAGE,
  REMOVE_MESSAGE,
};
