export const CHANGE_INIT_STATUS = 'CHANGE_INIT_STATUS';
export const SET_ADDRESS = 'SET_ADDRESS';
export const ADD_WALLET = 'ADD_WALLET';
export const SET_HD_KEY = 'SET_HD_KEY';
export const SET_BALANCE = 'SET_BALANCE';
export const SET_HD_CACHE_BY_TYPE = 'SET_HD_CACHE_BY_TYPE';

export default {
  CHANGE_INIT_STATUS,
  SET_ADDRESS,
  ADD_WALLET,
  SET_HD_KEY,
  SET_BALANCE,
  SET_HD_CACHE_BY_TYPE,
};
