const SETTINGS = 'INPAGE_PROVIDER_SETTINGS_EVENT';
const RESPONSE = 'INPAGE_PROVIDER_RESPONSE_EVENT';
const ERROR = 'INPAGE_PROVIDER_ERROR_EVENT';
const REQUEST = 'INPAGE_PROVIDER_REQUEST_EVENT';

export const INPAGE_EVENT = Object.freeze({
  SETTINGS,
  RESPONSE,
  ERROR,
  REQUEST,
});
