const SETTINGS = 'INPAGE_PROVIDER_SETTINGS_EVENT';
const RESPONSE = 'INPAGE_PROVIDER_RESPONSE_EVENT';
const MESSAGE = 'INPAGE_PROVIDER_MESSAGE_EVENT';

export const INPAGE_EVENT = Object.freeze({
  SETTINGS,
  RESPONSE,
  MESSAGE,
});

export const INPAGE_ID_PREFIX = 'ep_';
