const SETTINGS = 'INPAGE_PROVIDER_SETTINGS_EVENT';
const RESPONSE = 'INPAGE_PROVIDER_RESPONSE_EVENT';
const REQUEST = 'INPAGE_PROVIDER_REQUEST_EVENT';

export const INPAGE_EVENT = Object.freeze({
  SETTINGS,
  RESPONSE,
  REQUEST,
});

export const INPAGE_ID_PREFIX = 'ep_';
