export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const SET_TRANSACTION_HISTORY = 'SET_TRANSACTION_HISTORY';
export const SET_PENDING_TRANSACTIONS_FILTER_ID =
  'SET_PENDING_TRANSACTIONS_FILTER_ID';
