<template lang="html">
  <v-modal
    class="is-dark"
    @close="close"
  >
    <template slot="header">Two Factor Authentication</template>
    <div v-if="secret">
      <p class="lead">To protect your account, we strongly recommend enabling
      two factor authentication. Once enabled, you will be able to log in by
      entering a code generated by an authenticator app.</p>

      <p class="lead">Scan the QR code below into <strong>Google
      Authenticator</strong>. If you are unable to scan the code, you can
      also enter the secret manually.</p>

    </div>
    <v-form
      id="twoFactorAuth"
      @submit="confirm"
      :isFormValid="isFormValid"
    >
      <div
        v-if="secret && email"
        class="field"
      >
        <div class="has-text-centered">
          <img :src="qrCodeSrc">
        </div>
        <p class="subtitle">Write down the recovery secret below:</p>
        <label class="label">Secret</label>
        <p class="subtitle twofa-secret">
          <strong>{{ secret }}</strong>
        </p>
      </div>
      <p class="subtitle">Enter the 6 digit code generated by your
      authenticator app.</p>
      <v-input
        v-model="code"
        type="number"
        size="6"
        label="Verification Code"
        name="verificationCode"
        v-validate="'required|digits:6'"
        data-vv-name="verificationCode"
        :error="errors.first('verificationCode')"
        data-test="input-two-auth-code"
        autofocus
      />
    </v-form>
    <div
      slot="footer"
      class="buttons"
    >
      <v-button
        :loading="isLoading"
        :disabled="!isFormValid"
        form="twoFactorAuth"
        class-name="is-primary is-medium"
        data-test="submit-two-auth-modal"
      >
        Verify
      </v-button>
    </div>
  </v-modal>
</template>

<script>
import formMixin from '@/mixins/form';

export default {
  name: 'TwoFactorAuthModal',
  props: {
    secret: {
      type: String,
      default: '',
    },
    email: {
      type: String,
      default: '',
    },
    isLoading: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      code: null,
    };
  },
  computed: {
    qrCodeSrc() {
      const otpAuthUri = `otpauth://totp/Endpass:${this.email}?secret=${
        this.secret
      }`;

      return `https://chart.googleapis.com/chart?chs=166x166&chld=L|0&cht=qr&chl=${otpAuthUri}`;
    },
  },
  methods: {
    confirm() {
      this.$emit('confirm', this.code);
    },
    close() {
      this.$emit('close');
    },
  },
  mixins: [formMixin],
};
</script>
