export const SAVE_TOKEN = 'SAVE_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';
export const SAVE_TOKENS = 'SAVE_TOKENS';
export const SAVE_TRACKED_TOKENS = 'SAVE_TRACKED_TOKENS';
export const SAVE_TOKEN_PRICE = 'SAVE_TOKEN_PRICE';
export const SAVE_TOKENS_PRICES = 'SAVE_TOKENS_PRICES';
export const SAVE_TOKEN_INFO = 'SAVE_TOKEN_INFO';
export const SAVE_TOKENS_BALANCES = 'SAVE_TOKENS_BALANCES';

export const SET_LOADING = 'SET_LOADING';
export const SET_TOKENS_PRICES = 'SET_TOKENS_PRICES';
export const SET_NETWORK_TOKENS = 'SET_NETWORK_TOKENS';
export const ADD_NETWORK_TOKENS = 'ADD_NETWORK_TOKENS';
export const ADD_USER_TOKEN = 'ADD_USER_TOKEN';
export const REMOVE_USER_TOKEN = 'REMOVE_USER_TOKEN';
export const SET_USER_TOKENS = 'SET_USER_TOKENS';
export const SET_TOKENS_BY_ADDRESS = 'SET_TOKENS_BY_ADDRESS';
export const SET_BALANCES_BY_ADDRESS = 'SET_BALANCES_BY_ADDRESS';
