export const SET_LOADING = 'SET_LOADING';
export const ADD_NETWORK_TOKENS = 'ADD_NETWORK_TOKENS';
export const ADD_TOKENS_PRICES = 'ADD_TOKENS_PRICES';
export const SET_USER_TOKENS = 'SET_USER_TOKENS';
export const SET_BALANCES_BY_ADDRESS = 'SET_BALANCES_BY_ADDRESS';
export const SET_TOKENS_BY_ADDRESS = 'SET_TOKENS_BY_ADDRESS';
export const SET_INTERVAL_ID = 'SET_INTERVAL_ID';
