export const SET_WEB3_CONNECTION_STATUS = 'SET_WEB3_CONNECTION_STATUS';
export const SET_API_CONNECTION_STATUS = 'SET_API_CONNECTION_STATUS';
export const SET_SYNC_STATUS = 'SET_SYNC_STATUS';
export const ADD_API_ERROR_ID = 'ADD_API_ERROR_ID';
export const REMOVE_API_ERROR_ID = 'REMOVE_API_ERROR_ID';
