name: tests
on:
  pull_request:
    branches:
      - master
      - release

jobs:
  tests:
    strategy:
      matrix:
        test_suite: [unit, e2e]

    runs-on: ubuntu-16.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: get pr   
      uses: 8BitJonny/gh-get-current-pr@master
      id: PR
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        filterOutClosed: true

    - run: echo "Your PR is ${prNumber} and its JSON is ${prJSON}"
      if: success() && steps.PR.outputs.number
      env:
        prNumber: ${{ steps.PR.outputs.number }}
        prJSON: ${{ steps.PR.outputs.pr }}
 
    - name: Setup node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Start dev server
      run: yarn dev & sleep 5

    - name: ${{matrix.test_suite}} tests
      run: yarn ${{matrix.test_suite}}

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      continue-on-error: true
      with:
        type: ${{ job.status }}
        job_name: 'wallet ${{matrix.test_suite}} tests'
        username: 'GitHub Actions'
        icon_emoji: ':github:'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
