name: tests
on:
  pull_request:
    branches:
      - master
      - release

jobs:
  tests:
    strategy:
      matrix:
        test_suite: [unit, e2e]

    runs-on: ubuntu-16.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Start dev server
      run: yarn dev & sleep 5

    - name: ${{ matrix.test_suite }} tests
      run: yarn ${{ matrix.test_suite }}

    - name: Slack notification
      uses: rtCamp/action-slack-notify@v2.0.2
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: GitHub Actions
        SLACK_COLOR: '#2AD624'
        SLACK_ICON_EMOJI: ':github:'
        SLACK_MESSAGE: 'Tests succeeded :rocket:'
        SLACK_TITLE: '*${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}* - Wallet ${{ matrix.test_suite }} tests'

    - name: Slack notification
      uses: rtCamp/action-slack-notify@v2.0.2
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: GitHub Actions
        SLACK_COLOR: '#EC4926'
        SLACK_ICON_EMOJI: ':github:'
        SLACK_MESSAGE: 'Tests failed :fire:'
        SLACK_TITLE: '*${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}* - Wallet ${{ matrix.test_suite }} tests'