name: tests
on:
  pull_request:
    branches:
      - master
      - release

jobs:
  tests:
    strategy:
      matrix:
        test_suite: [unit, e2e]

    runs-on: ubuntu-16.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Get pull request comment
      uses: actions/github-script@0.9.0
      id: github_script
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.pull.number
          })

    - name: get json
      run: |
        echo "${{ steps.github_script.outputs.result }}"
 
    - name: Setup node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Start dev server
      run: yarn dev & sleep 5

    - name: ${{matrix.test_suite}} tests
      run: yarn ${{matrix.test_suite}}

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      continue-on-error: true
      with:
        type: ${{ job.status }}
        job_name: 'wallet ${{matrix.test_suite}} tests'
        username: 'GitHub Actions'
        icon_emoji: ':github:'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
