name: wallet release
on:
  push:
    branches:
      - release
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:

    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Setup node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build:staging

    - name: Deploy to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: wallet-staging.endpass.com
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'dist/'

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: 'wallet build and deploy'
        username: 'GitHub Actions'
        icon_emoji: ':github:'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
